### ISSUE TITLE
Can't start rhe app

### ISSUE THREAD

**Issue by CesarHerreraG** [ubports/gallery-app#2]
https://ln.sync.com/dl/17046e460/eych67dj-h6f3ci2i-grjtar4a-33in5nde
This is obtained when the app is open. Passing the time it may be imposible open the app.

**Comment by CesarHerreraG** [comment]
the app

**Comment by CesarHerreraG** [comment]
https://ln.sync.com/dl/c0f6ead40/68hiifaj-ek58kwex-2q8ieftc-v9fzzda7

https://ln.sync.com/dl/ce8d18350/2kx58cmv-c8euixu3-h3p4fewh-jndxncvy

**Comment by CesarHerreraG** [comment]
I don't know another way of put the files. Sorry.

**Comment by CesarHerreraG** [comment]
Said in a previous review:
I install Gallery in the store of Ubuntu. Initially I can open the app and may open a picture. But after some time the app doesn't open and I can't open a picture. The app may even lost their icon.
Phone: BQ E4.5 with r3
I have the same problem with OpenStore app.

**Comment by CesarHerreraG** [comment]
Now r5

**Comment by Flohack74** [comment]
@bhdouglass Can you think of any cause that would make openstore app behave like that?

**Comment by CesarHerreraG** [comment]
No. Gallery and Openstore behabes the same. When I install them they open. But after a time they don't. Even their i on doesn't appear. Althow may reappear. But the only way to function is remove them an reinstall.
Perhaps I have to reinstall the O.S.
In this case I don't know the best way of doing it.
Thanks a lot.

**Comment by bhdouglass** [comment]
@Flohack74 I'm not sure, what exactly is the problem here and can we get some logs for the OpenStore?

**Comment by CesarHerreraG** [comment]
I have send 3 links to logs.
I install the apps Gallery and OpenStore and in the first time they go. But after some time they don't open.

**Comment by CesarHerreraG** [comment]
https://ln.sync.com/dl/ba299fe90/gisngrh3-p6krrwen-gxu59dup-u6xwcnxv
