### ISSUE TITLE
Wrong translation for sharing

### ISSUE THREAD

**Issue by ernesst** [ubports/gallery-app#35]
Gents,

When i need to share an image, in the menu i have the choice to "compartir". i guess there is a translation error/typo, on my english phone.

![image](https://user-images.githubusercontent.com/11337464/30934253-a1e7f764-a392-11e7-9a19-ed45dfae8a10.png)

**Comment by StefWe** [comment]
Is this fixed or should i check the translation?

**Comment by Flohack74** [comment]
Plz check in https://translate.ubports.com/projects/ubports/gallery-app/

**Comment by StefWe** [comment]
Thank you for this link.
If i build the app i found some translation fault to german, but the problem is the de.po file. In line 99 https://github.com/ubports/gallery-app/blob/master/po/de.po there are some text. When i remove this text, the translation works.
Is this file generated by weblate or how can we fix this?

**Comment by Flohack74** [comment]
Please do not touch the po files directly, I will take care for this.

**Comment by StefWe** [comment]
@Flohack74 thank you. I found another issue. The structure of the .pot file is not working at some points.
original:
**#: rc/qml/EventsOverview.qml:76 rc/qml/PhotosOverview.qml:85
msgid "Delete 1 photo"
msgstr ""**

**#: rc/qml/EventsOverview.qml:81 rc/qml/PhotosOverview.qml:90
#, qt-format
msgid "Delete %1 photos"
msgstr ""**

and it works if i changed it in the following format:
**#: rc/qml/EventsOverview.qml:80 rc/qml/PhotosOverview.qml:85
#, qt-format
msgid "Delete %1 photo"
msgid_plural "Delete %1 photos"
msgstr[0] ""
msgstr[1] ""**

should i made a pull request for the .pot file change or do you fix this?

**Comment by StefWe** [comment]
i try to make a PR, but i get following info from atom
**remote: Permission to ubports/gallery-app.git denied to StefWe**
Is there anything i made wrong or is it only missing permissions

**Comment by Flohack74** [comment]
Yes, you need to fork the App to your user, you are not part of the organization and therefore you dont have write access.

**Comment by StefWe** [comment]
The github workflow is completely new for me, thank you for your help

**Comment by Flohack74** [comment]
But you did it! So finally we got this fixed, and I translated already the new German words ;)

**Comment by StefWe** [comment]
I found another wrong translation

![screenshot20180501_204510815](https://user-images.githubusercontent.com/35935077/39487851-c272ead2-4d80-11e8-8272-1db925bd48f9.png)

but this is from the  ubuntu-ui-extras/modules/Ubuntu/Components/Extras/PhotoEditor.qml and look correct translatetd in the german version, the only thing is in line 84/85 https://github.com/StefWe/ubuntu-ui-extras/blob/xenial/po/de.po

Any idea what we can do to fix this?

**Comment by Flohack74** [comment]
I added this to our Weblate server: https://translate.ubports.com/projects/ubports/ubuntu-ui-extras/ - does this help?

**Comment by Flohack74** [comment]
Ok perfect!
