### ISSUE TITLE
Personal Collection

### ISSUE THREAD

**Issue by CesarHerreraG** [ubports/gallery-app#71]
You may want to have some photos selected to view only them. Special photos that you want ro see without searching everything. Ready to see them without difficulty.

**Comment by TronFortyTwo** [comment]
I think I miss the point of this request; what's the difference with creating a "Personal" album and putting there the photos you want to?

**Comment by StefWe** [comment]
You can create a album and select some picture you want to add to this album.

Next time you only have to open your album

**Comment by StefWe** [comment]
to slow 👍

**Comment by CesarHerreraG** [comment]
I didn't know it. You are right. Thanks a lot.

**Comment by StefWe** [comment]
Can we close this issue?

Is the album function ok for your needs?

**Comment by CesarHerreraG** [comment]
Yes you can close. Thanks.
