### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by Flohack74** [ubports/gallery-app#8]
We need to check usage of i8n.tr() functions, if they correspond to a string in the .pot file of the App. Then, use poedit to fix all languages we know, until we got translation service working again.

See screenshots:

**Comment by Flohack74** [comment]
![grafik](https://user-images.githubusercontent.com/16186470/27103359-a98bdb82-5088-11e7-8e9d-6b0681717f85.png)
![grafik](https://user-images.githubusercontent.com/16186470/27103365-adf063be-5088-11e7-8d08-02a25e977617.png)

**Comment by TronFourtyTwo** [comment]
Here I am to work this out. I will write here the progress.

**Comment by nfsprodriver** [comment]
Should we call that a "bug"?

**Comment by StefWe** [comment]
With the new .dot file and the removed #, fuzzy in the .po files this wrong translations from this issue are fixed.
I think we can close this issue

**Comment by Flohack74** [comment]
Good!
