### ISSUE TITLE
Russian translate issue "Date" in gallery-app

### ISSUE THREAD

**Issue by idekovets** [ubports/gallery-app#89]
In gallery wrong displayed Date. Instead "Ноябрь 2018" (November 2018) shown "МММ гггг". I already update translation on UBports Weblate. Please update gallery-app.

Thanks!

**Comment by StefWe** [comment]
Now we need someone how made a peer review?

![screenshot_20181116_081836](https://user-images.githubusercontent.com/35935077/48603918-50751d80-e978-11e8-805e-b2f795a140f6.png)

**Comment by StefWe** [comment]
Your translation is not the problem.
I believe that someone who admins the weblate service must say that weblate should accept that.

But maybe I'm wrong about this too.

**Comment by idekovets** [comment]
Accepted

**Comment by StefWe** [comment]
Perfect. Thank you very much for the fast help.
With the next version this should be fixed.

**Comment by idekovets** [comment]
OK. Thanks!

**Comment by Flohack74** [comment]
Translations are only pushed once per week during the night from Sat to Sun. So lets see tomorrow ;)

**Comment by idekovets** [comment]
Thanks!Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail17.11.2018, 11:48, "Florian Leeber" <notifications@github.com>:Translations are only pushed once per week during the night from Sat to Sun. So lets see tomorrow ;)

**Comment by idekovets** [comment]
> Translations are only pushed once per week during the night from Sat to Sun. So lets see tomorrow ;)

Still

**Comment by StefWe** [comment]
at the moment the translation is a open pull request as you can see here https://github.com/ubports/gallery-app/pull/86
Now someone needs to merge this into the master tree.
If this is done, we need to bring a new version of the app to the open-store

**Comment by idekovets** [comment]
> at the moment the translation is a open pull request as you can see here #86
> Now someone needs to merge this into the master tree.
> If this is done, we need to bring a new version of the app to the open-store

OK OK
Thanks!

**Comment by StefWe** [comment]
on the next gallery-app update you get via open-store this translation should be fixed
